#
# This playbook install custom kernel
#

- hosts: ampis
  remote_user: root
  tasks:
    - name: Install kernel modules
      synchronize:
        src: ../kernel-bin/lib/modules/
        dest: /lib/modules/
    - name: Install kernel firmware files
      synchronize:
        src: ../kernel-bin/lib/firmware/
        dest: /lib/firmware/
    - name: Install kernel boot files
      synchronize:
        src: ../kernel-bin/boot/
        dest: /boot/
        archive: no
        times: yes

# vi: sw=2 sts=2 et filetype=yaml
